
   
 name: wod-workflow
    
 on:
   schedule:
     - cron: "*/5 * * * *" #runs at 00:00 UTC everyday

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: checkout repo content
         uses: actions/checkout@v2 # checkout the repository content to github runner.
       - name: setup python
         uses: actions/setup-python@v2
         with:
           python-version: 3.8 #install the python needed
       - name: install deenencies
         run: |
           python -m pip install --upgrade pip
           pip install flake8 pytest
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       - name: execute py script # run the run.py to get the latest data
         env: # Or as an environment variable
            TEAMS_ACCESS_TOKEN: ${{ secrets.TEAMS_ACCESS_TOKEN }}
         run: |
            python3 chatops.py
